# Generated by Django 3.2.3 on 2021-05-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_smartphone_sd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
